### ISSUE TITLE
URL not accepted

### ISSUE THREAD

**Issue by outbreakprepared** [open-covid-data/healthmap-gdo-temp#452] opened 2020-07-07 10:56 UTC
**Describe the bug**
Source ID was not accepted (http://187.191.75.115/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip)

**To Reproduce**
Copy link: http://187.191.75.115/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip into source URL file

**Expected behavior**
accepted URL

![Screenshot 2020-07-07 at 11 54 50](https://user-images.githubusercontent.com/63060519/86770517-b67c5000-c048-11ea-88bf-9c2ca20c99cf.png)

**Environment (please complete the following information):**
Google Chrome is up to date
Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by allysonjp715** [comment] 2020-07-08 12:15
Duplicate of #446

**Closed by allysonjp715** 2020-07-08 12:15 UTC
Labels: bug
