### ISSUE TITLE
(information) tab for information for curators.

### ISSUE THREAD

**Issue by outbreakprepared** [open-covid-data/healthmap-gdo-temp#456] opened 2020-07-07 11:11 UTC
**Is your feature request related to a problem? Please describe.**
Add a tab to describe for each section what should be entered (as well as do's and don'ts).

**Describe the solution you'd like**
Have a little window when hovering over let's say 'location' and explain briefly what this section is about.

**Comment by allysonjp715** [comment] 2020-07-08 12:09
Do the ? tooltips cover this request? Those can be seen in https://www.figma.com/file/9HJlRkTBCMEQdkJ6WQJYkv/061120_Global.Health-Line?node-id=82%3A10099

We will add them once we have the copy to enter in the tooltips.

**Comment by sratcliffe118** [comment] 2020-07-08 16:38
Duplicate of #438

**Closed** 2020-07-08 16:38 UTC
Labels: Documentation
