### ISSUE TITLE
Start adding tooltips to the various case form fields

### ISSUE THREAD

**Issue by attwad** [open-covid-data/healthmap-gdo-temp#625] opened 2020-07-27 07:57 UTC
**Is your feature request related to a problem? Please describe.**
Was mentioned a few times during the UX review, we can start adding a few tooltips here and there to make it obvious what some things are meant to be.

https://material-ui.com/components/tooltips/

![image](https://user-images.githubusercontent.com/1255432/88517719-97416480-cfef-11ea-9963-45d385a02bde.png)

**Comment by allysonjp715** [comment] 2020-07-27 08:32
Duplicate of #562
Code is in place once copy is written: https://github.com/open-covid-data/healthmap-gdo-temp/blob/main/verification/curator-service/ui/src/components/common-form-fields/FieldTitle.tsx

**Closed by allysonjp715** 2020-07-27 08:32 UTC
Labels: Curator Portal, UX research

**Comment by attwad** [comment] 2020-07-27 08:35
ohh nice :) thanks
