### ISSUE TITLE
No confirmation date given BUT date of symptom onset and hospital consultation provided

### ISSUE THREAD

**Issue by outbreakprepared** [open-covid-data/healthmap-gdo-temp#453] opened 2020-07-07 11:01 UTC
**Is your feature request related to a problem? Please describe.**

I was unable to submit the case without information on the date of confirmation.

**Describe the solution you'd like**

Allow to upload case even though date of confirmation is missing as long as a date is provided in the entry.

**Describe alternatives you've considered**
This is prone to errors and curators making assumptions. I.e., I could decide to put date of first clinical consultation as the date of confirmation but this is not correct.

![Screenshot 2020-07-07 at 11 53 37](https://user-images.githubusercontent.com/63060519/86771055-82edf580-c049-11ea-8a28-e3d9cb08b0a5.png)

**Comment by allysonjp715** [comment] 2020-07-08 12:16
@sratcliffe118 should we remove the restriction that confirmation date and method of confirmation be required?

**Comment by allysonjp715** [comment] 2020-07-08 15:02
Duplicate of #457

**Closed by allysonjp715** 2020-07-08 15:02 UTC
Labels: enhancement
