### ISSUE TITLE
Content and help copy for the manual entry form

### ISSUE THREAD

**Issue by sratcliffe118** [open-covid-data/healthmap-gdo-temp#438] opened 2020-07-03 10:20 UTC
Need to provide detailed content and copy for the manual entry form & the help copy to assist curators as they navigate through the form

**Comment by sratcliffe118** [comment] 2020-07-08 16:00
Copy matrix first draft[https://docs.google.com/spreadsheets/d/1mPYrNaO799ZDSTEgCn2WSHEGlwYYxuG2MG9t5TGpN0E/edit](url)

**Comment by allysonjp715** [comment] 2020-07-17 10:55
Duplicate of #562

**Closed by allysonjp715** 2020-07-17 10:55 UTC
Labels: P1 Launch blocker, Product
