### ISSUE TITLE
Source URL: Validation error remains in place even when fixed

### ISSUE THREAD

**Issue by sratcliffe118** [open-covid-data/healthmap-gdo-temp#443] opened 2020-07-06 13:06 UTC
Steps to recreate:
1. Enter incorrect formatted source URL
2. Validation error triggered
3. En-enter with valid format. 
4. validation error message remains with Red X
See screenshot

Expected behavior:
The validation error should disappear when a valid url is entered and a green tick should be displayed in the top left hand nav
![Screen Shot 2020-07-06 at 2 05 51 PM](https://user-images.githubusercontent.com/63205311/86596256-d1d85400-bf91-11ea-84b5-d78fa505a27a.png)

**Comment by sratcliffe118** [comment] 2020-07-06 13:09
URL from data source: https://news.ontario.ca/mohltc/en/2020/01/ontario-confirms-first-case-of-wuhan-novel-coronavirus.html

**Comment by allysonjp715** [comment] 2020-07-08 12:15
Duplicate of #446

**Closed by allysonjp715** 2020-07-08 12:15 UTC
Labels: P1 Launch blocker, bug
